// Application Limits
export const LIMITS = {
  // User Limits
  MAX_USERS_PER_ORGANIZATION: 1000,
  MAX_SESSIONS_PER_USER: 10,
  MAX_DEVICES_PER_USER: 5,
  MAX_API_KEYS_PER_USER: 10,

  // Project Limits
  MAX_PROJECTS_PER_ORGANIZATION: 1000,
  MAX_TASKS_PER_PROJECT: 10000,
  MAX_MEMBERS_PER_PROJECT: 100,
  MAX_TAGS_PER_PROJECT: 50,

  // Task Limits
  MAX_TASKS_PER_USER: 10000,
  MAX_SUBTASKS_PER_TASK: 100,
  MAX_DEPENDENCIES_PER_TASK: 20,
  MAX_ATTACHMENTS_PER_TASK: 50,
  MAX_COMMENTS_PER_TASK: 1000,

  // Time Entry Limits
  MAX_TIME_ENTRIES_PER_DAY: 100,
  MAX_TIME_ENTRIES_PER_PROJECT: 10000,
  MAX_TIME_ENTRIES_PER_TASK: 1000,

  // Organization Limits
  MAX_TEAMS_PER_ORGANIZATION: 100,
  MAX_MEMBERS_PER_TEAM: 50,
  MAX_WEBHOOKS_PER_ORGANIZATION: 50,
  MAX_INTEGRATIONS_PER_ORGANIZATION: 20,

  // File Limits
  MAX_FILE_SIZE_MB: 10,
  MAX_FILES_PER_REQUEST: 10,
  MAX_TOTAL_SIZE_MB: 100,

  // API Limits
  MAX_REQUESTS_PER_MINUTE: 100,
  MAX_REQUESTS_PER_HOUR: 1000,
  MAX_REQUESTS_PER_DAY: 10000,
} as const;
